[theme]
name = "native"
[theme.overrides]
good_bg = "#4A8B3F"
idle_fg = "#FFFFFF"
info_bg = "#B46442"
warning_bg = "#FDD500"
critical_bg = "#F44747"
[icons]
name = "awesome"

[[block]]
block = "focused_window"
max_width = 20
show_marks = "visible"

[[block]]
block = "temperature"
collapsed = false
scale = "celsius"
good = 40
idle = 45
info = 55
warning = 70
chip = "k10temp-pci-00c3"
format = "CPU: {average}C"
interval = 0.35

[[block]]
block = "custom"
cycle = ["getgov", "getgov"]
on_click = "sudo togglecpugov"
interval = 0.5

[[block]]
block = "nvidia_gpu"
label = "GPU:"
show_utilization = false
show_memory = false
show_temperature = true
show_power_draw = true
show_clocks = false
show_fan_speed = true
interval = 0.65

[[block]]
block = "memory"
display_type = "memory"
clickable = true
format_mem = "{mem_used} /{mem_total}"
format_swap = "{swap_used} /{swap_total}"
interval = 2

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {used} /{total}"
unit = "GB"
alert = 90
warning = 80

[[block]]
block = "music"
#player = "mpd"
player = "vlc"
hide_when_empty = true
format = "{title}"
buttons = ["play"]

[[block]]
block = "sound"
driver = "pulseaudio"
format = "{output_name} {volume}"
device_kind = "sink"
max_vol = 100
on_click = "toggleaudiodevice"
[block.mappings]
"alsa_output.pci-0000_27_00.1.hdmi-stereo-extra1" = "Speakers"
"alsa_output.usb-Kingston_HyperX_Virtual_Surround_Sound_00000000-00.iec958-stereo" = "Headphones"

[[block]]
block = "net"
device = "enp34s0"
format = "{speed_down;_M*_b} {speed_up;_M*_b}"
interval = 0.5

[[block]]
block = "custom"
command = "printf 'up: ' && sysuptime"
interval = 1

[[block]]
block = "custom"
command = "uname -r"

[[block]]
block = "time"
interval = 1
format = "%d.%m.%Y %H:%M:%S"
timezone = "Europe/Berlin"
