#!/bin/zsh
bg=$(ls ~/Pictures/Backgrounds/*.(png|jpg|jpeg) | sxiv -tio)

if [[ -z $bg ]]; then
    echo "You have to select an image!"
    exit 1
elif ! [[ $bg =~ '^\/home\/philip\/Pictures\/Backgrounds\/.*\.(png|jpg|jpeg)$'  ]]; then
    echo "Only select one image!"
    exit 2
else
    feh --bg-scale $bg
    ext=$bg:t:e
    rm $(ls ~/Pictures/curbg/bg.*)
    cp -r "$bg" "/home/philip/Pictures/curbg/bg.$ext"
fi
