#!/bin/sh
monitor="$1"
gamma="$2"

if [ "$1" == "1" ]; then
    xrandr --output HDMI-0 --gamma "$2":"$2":"$2"
elif [ "$1" == "2" ]; then
    xrandr --output DP-0 --gamma "$2":"$2":"$2"
elif [ "$1" == "0" ]; then
    xrandr --output DP-2 --gamma "$2":"$2":"$2"
elif [ "$1" == "all" ]; then
    xrandr --output DP-0 --gamma "$2":"$2":"$2"
    xrandr --output DP-2 --gamma "$2":"$2":"$2"
    xrandr --output HDMI-0 --gamma "$2":"$2":"$2"
fi
