#!/usr/bin/zsh
#curdev=$(pacmd list-sinks | grep -e '* index:')
#curindex=$curdev[-1]
dev=$(pacmd stat | grep -e "Default sink name: ")
curdev=$dev[20,${#dev}]
headset="alsa_output.usb-Kingston_HyperX_Virtual_Surround_Sound_00000000-00.iec958-stereo"
speaker="alsa_output.pci-0000_27_00.1.hdmi-stereo"

if [ "$curdev" = "$headset" ]; then
    pacmd set-default-sink "$speaker"
elif [ "$curdev" = "$speaker" ]; then
    pacmd set-default-sink "$headset"
fi
