#!/usr/bin/zsh
dev=$(pactl info | grep -e "Default Sink: ")
curdev=$dev[15,${#dev}]
devices=("${(@f)$(pactl list sinks | grep -e "Name: " | cut -d: -f2- | sed 's/^ *//g')}")

for ((i = 1; i <= $#devices; i++)); do
    if [ "${devices[$i]}" = "$curdev" ] && [ $i -lt $#devices ]; then
        pactl set-default-sink "${devices[$i + 1]}"
        break
    elif [ $i = $#devices ]; then
        pactl set-default-sink "${devices[1]}"
    else
        continue
    fi
done
